name: Navidrome | Build and Publish

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 0'

permissions:
  contents: write
  packages: write

jobs:
  check-versions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./navidrome
    outputs:
      rebuild: ${{ steps.check.outputs.rebuild }}
      version_metadata: ${{ steps.meta.outputs.content }}
      navidrome_version: ${{ steps.get_versions.outputs.navidrome }}
      ffmpeg_version: ${{ steps.get_versions.outputs.ffmpeg }}
      opus_version: ${{ steps.get_versions.outputs.opus }}
      lame_version: ${{ steps.get_versions.outputs.lame }}
      taglib_version: ${{ steps.get_versions.outputs.taglib }}
      zlib_version: ${{ steps.get_versions.outputs.zlib }}
    steps:
      - uses: actions/checkout@v6

      - name: Get latest versions
        id: get_versions
        run: |
          NAVIDROME=$(git ls-remote --tags --sort='v:refname' https://github.com/navidrome/navidrome.git | grep "refs/tags/v" | grep -v "\^{}" | tail -n1 | sed 's/.*\///' | sed 's/^v//')
          FFMPEG=$(git ls-remote --tags --sort='v:refname' https://github.com/FFmpeg/FFmpeg.git | grep "refs/tags/n" | grep -v "\-dev" | grep -v "\^{}" | tail -n1 | sed 's/.*\///' | sed 's/^n//')
          OPUS=$(git ls-remote --tags --sort='v:refname' https://github.com/xiph/opus.git | grep "refs/tags/v" | grep -v "\^{}" | tail -n1 | sed 's/.*\///' | sed 's/^v//')
          LAME=$(git ls-remote --tags --sort='v:refname' https://salsa.debian.org/multimedia-team/lame.git | grep "refs/tags/debian/" | grep -v "svn" | tail -n1 | sed 's/.*\///' | sed 's/debian\///')
          TAGLIB=$(git ls-remote --tags --sort='v:refname' https://github.com/taglib/taglib.git | grep "refs/tags/v" | grep -v "\^{}" | tail -n1 | sed 's/.*\///' | sed 's/^v//')
          ZLIB=$(git ls-remote --tags --sort='v:refname' https://github.com/madler/zlib.git | grep "refs/tags/v" | grep -v "\^{}" | tail -n1 | sed 's/.*\///' | sed 's/^v//')
          
          echo "navidrome=${NAVIDROME}" >> $GITHUB_OUTPUT
          echo "ffmpeg=${FFMPEG}" >> $GITHUB_OUTPUT
          echo "opus=${OPUS}" >> $GITHUB_OUTPUT
          echo "lame=${LAME}" >> $GITHUB_OUTPUT
          echo "taglib=${TAGLIB}" >> $GITHUB_OUTPUT
          echo "zlib=${ZLIB}" >> $GITHUB_OUTPUT

      - name: Check for Changes
        id: check
        run: |
          FILE="package-versions.txt"
          REBUILD=false
          NAVIDROME="${{ steps.get_versions.outputs.navidrome }}"
          
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            REBUILD=true
          elif [ ! -f $FILE ] || ! grep -q "$NAVIDROME" $FILE; then
            REBUILD=true
          fi
          echo "rebuild=$REBUILD" >> $GITHUB_OUTPUT

      - name: Generate Version Metadata
        id: meta
        run: |
          {
            echo "# Navidrome Release Versions"
            echo "navidrome-${{ steps.get_versions.outputs.navidrome }}"
            echo "ffmpeg-${{ steps.get_versions.outputs.ffmpeg }}"
            echo "opus-${{ steps.get_versions.outputs.opus }}"
            echo "mp3lame-${{ steps.get_versions.outputs.lame }}"
            echo "taglib-${{ steps.get_versions.outputs.taglib }}"
            echo "zlib-${{ steps.get_versions.outputs.zlib }}"
          } > meta.txt
          CONTENT=$(cat meta.txt | base64 -w 0)
          echo "content=$CONTENT" >> $GITHUB_OUTPUT

  build:
    needs: check-versions
    uses: ./.github/workflows/_build_template.yml
    with:
      image_name: navidrome
      context: ./navidrome
      dockerfile: ./navidrome/Dockerfile
      build_args: |
        NAVIDROME_VERSION=${{ needs.check-versions.outputs.navidrome_version }}
        FFMPEG_VERSION=${{ needs.check-versions.outputs.ffmpeg_version }}
        OPUS_VERSION=${{ needs.check-versions.outputs.opus_version }}
        MP3LAME_VERSION=${{ needs.check-versions.outputs.lame_version }}
        TAGLIB_VERSION=${{ needs.check-versions.outputs.taglib_version }}
        ZLIB_VERSION=${{ needs.check-versions.outputs.zlib_version }}
        CFLAGS=-O3 -fstack-protector-strong -D_FORTIFY_SOURCE=2
        CXXFLAGS=-O3 -fstack-protector-strong -D_FORTIFY_SOURCE=2
      rebuild: ${{ needs.check-versions.outputs.rebuild == 'true' }}
      version_metadata: ${{ needs.check-versions.outputs.version_metadata }}
      extra_variants: |
        [
          {
            "platform": "linux/arm64",
            "runner": "ubuntu-24.04-arm",
            "suffix": "rpi4",
            "build_args": "CFLAGS=-O3 -mcpu=cortex-a72 -fstack-protector-strong -D_FORTIFY_SOURCE=2\nCXXFLAGS=-O3 -mcpu=cortex-a72 -fstack-protector-strong -D_FORTIFY_SOURCE=2"
          },
          {
            "platform": "linux/amd64",
            "runner": "ubuntu-latest",
            "suffix": "amd64-v3",
            "build_args": "CFLAGS=-O3 -march=x86-64-v3 -fstack-protector-strong -D_FORTIFY_SOURCE=2\nCXXFLAGS=-O3 -march=x86-64-v3 -fstack-protector-strong -D_FORTIFY_SOURCE=2"
          }
        ]
