name: Build and Publish Alfis

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write
  packages: write

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  check-versions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./alfis
    outputs:
      rebuild: ${{ steps.check.outputs.rebuild }}
      version_metadata: ${{ steps.meta.outputs.content }}
      alfis_version: ${{ steps.get_latest_release.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest alfis release tag
        id: get_latest_release
        run: |
          LATEST_TAG=$(git ls-remote --tags --sort='v:refname' https://github.com/Revertron/Alfis.git | grep "refs/tags/v" | grep -v "\^{}" | tail -n1 | sed 's/.*\///')
          echo "tag=${LATEST_TAG}" >> $GITHUB_OUTPUT

      - name: Check for latest package versions
        id: get_pkgs
        run: |
          docker run --rm alpine:latest sh -c "apk update >/dev/null && apk list rust cargo openssl-libs-static zlib-static pkgconf" | awk '{print $1}' | sort > current-packages.txt

      - name: Check for Changes
        id: check
        run: |
          FILE="package-versions.txt"
          REBUILD=false
          VERSION="${{ steps.get_latest_release.outputs.tag }}"
          
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            REBUILD=true
          elif [ ! -f $FILE ] || ! grep -q "$VERSION" $FILE; then
            REBUILD=true
          elif ! diff -q current-packages.txt <(grep -vE "^(alfis-|#)" $FILE | grep -v "^$" | sort); then
             REBUILD=true
          fi
          
          echo "rebuild=$REBUILD" >> $GITHUB_OUTPUT

      - name: Generate Version Metadata
        id: meta
        run: |
          {
            echo "# Alfis Versions"
            echo "alfis-${{ steps.get_latest_release.outputs.tag }}"
            echo ""
            echo "# Build Dependencies"
            cat current-packages.txt
          } > meta.txt
          CONTENT=$(cat meta.txt | base64 -w 0)
          echo "content=$CONTENT" >> $GITHUB_OUTPUT

  build:
    needs: check-versions
    uses: ./.github/workflows/_build_template.yml
    with:
      image_name: alfis
      context: ./alfis
      dockerfile: ./alfis/Dockerfile
      build_args: |
        ALFIS_VERSION=${{ needs.check-versions.outputs.alfis_version }}
      rebuild: ${{ needs.check-versions.outputs.rebuild == 'true' }}
      version_metadata: ${{ needs.check-versions.outputs.version_metadata }}
