name: Build and Publish I2PD Exporter

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write
  packages: write

jobs:
  check-versions:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./i2pd-exporter
    outputs:
      rebuild: ${{ steps.check.outputs.rebuild }}
      version_metadata: ${{ steps.meta.outputs.content }}
      app_version: ${{ steps.get_latest.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Get latest release
        id: get_latest
        run: |
          LATEST_TAG=$(git ls-remote --tags --sort='v:refname' https://github.com/Jercik/i2pd-exporter.git | grep "refs/tags/v" | grep -v "\^{}" | tail -n1 | sed 's/.*\///')
          echo "tag=${LATEST_TAG}" >> $GITHUB_OUTPUT

      - name: Check for Changes
        id: check
        run: |
          FILE="package-versions.txt"
          REBUILD=false
          VERSION="${{ steps.get_latest.outputs.tag }}"
          
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            REBUILD=true
          elif [ ! -f $FILE ] || ! grep -q "$VERSION" $FILE; then
            REBUILD=true
          fi
          
          echo "rebuild=$REBUILD" >> $GITHUB_OUTPUT

      - name: Generate Version Metadata
        id: meta
        run: |
          {
            echo "# I2PD Exporter Versions"
            echo "i2pd-exporter-${{ steps.get_latest.outputs.tag }}"
          } > meta.txt
          CONTENT=$(cat meta.txt | base64 -w 0)
          echo "content=$CONTENT" >> $GITHUB_OUTPUT

  build:
    needs: check-versions
    uses: ./.github/workflows/_build_template.yml
    with:
      image_name: i2pd-exporter
      context: ./i2pd-exporter
      dockerfile: ./i2pd-exporter/Dockerfile
      build_args: |
        APP_VERSION=${{ needs.check-versions.outputs.app_version }}
      rebuild: ${{ needs.check-versions.outputs.rebuild == 'true' }}
      version_metadata: ${{ needs.check-versions.outputs.version_metadata }}
